version: 2

sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    description: 'default customers data from snowflake db'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: CUSTOMER
        description: 'CUSTOMERS DATA'
